# render.yaml
services:
  - type: web
    name: art-gallery-demo # << YOUR UNIQUE APP NAME
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --no-input --clear
      python manage.py migrate
    startCommand: gunicorn gallery_config.wsgi:application --workers 2 --threads 2 --timeout 120
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5 # << YOUR PYTHON VERSION
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DATABASE_URL # Explicitly define that this web service needs a DB connection
        fromDatabase:
          name: artgallerydb # This MUST match the name of your database pserv below
          property: connectionString # Tells Render to inject the connection string
      # DJANGO_ALLOWED_HOSTS and DJANGO_CSRF_TRUSTED_ORIGINS will be set in Render Dashboard UI

  - type: pserv # PostgreSQL Database service
    name: artgallerydb # Name of your database service
    region: frankfurt
    plan: free
    # For a pserv that is a database, Render infers its nature based on the plan
    # and how other services (like 'web') connect to it using 'fromDatabase'.
    # You can optionally specify the engine version if needed:
    # postgresqlVersion: "15" 
    # No 'runtime' or 'startCommand' is needed here.