# render.yaml (Attempt with minimal pserv)
services:
  - type: web
    name: art-gallery-demo # << YOUR UNIQUE APP NAME
    # ... (rest of web service definition is THE SAME as Option 1) ...
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --no-input --clear
      python manage.py migrate
    startCommand: gunicorn gallery_config.wsgi:application --workers 2 --threads 2 --timeout 120
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5 # << YOUR PYTHON VERSION
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: artgallerydb # Must match the database service name below
          property: connectionString
      # DJANGO_ALLOWED_HOSTS and DJANGO_CSRF_TRUSTED_ORIGINS will be set in Render Dashboard UI

  - type: pserv # PostgreSQL Database service
    name: artgallerydb # Name of your database service
    region: frankfurt # Optional, but good to co-locate
    plan: free # This is key for Render to know it's a free tier DB
    # No other properties like 'engine' or specific postgresqlVersion.
    # Render should infer it's a PostgreSQL database from the 'plan'
    # and the fact that the web service is trying to connect to it for a DATABASE_URL.