# render.yaml (Attempt with explicit engine in pserv)
services:
  - type: web
    name: art-gallery-demo # << YOUR UNIQUE APP NAME
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --no-input --clear
      python manage.py migrate
    startCommand: gunicorn gallery_config.wsgi:application --workers 2 --threads 2 --timeout 120
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5 # << YOUR PYTHON VERSION
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: artgallerydb # Must match the database service name below
          property: connectionString
      # DJANGO_ALLOWED_HOSTS and DJANGO_CSRF_TRUSTED_ORIGINS will be set in Render Dashboard UI

  - type: pserv # PostgreSQL Database service
    name: artgallerydb # Name of your database service
    region: frankfurt
    plan: free
    engine: postgresql # <<<< ADDING THIS EXPLICITLY
    # postgresqlVersion: "15" # Optional: if you want to pin a specific version