# render.yaml
services:
  - type: web
    name: art-gallery-demo # << YOUR UNIQUE APP NAME
    env: python
    region: frankfurt 
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --no-input --clear 
      python manage.py migrate
    startCommand: gunicorn gallery_config.wsgi:application --workers 2 --threads 2 --timeout 120
    healthCheckPath: / # Optional, helps Render know your app is up
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5 # << YOUR PYTHON VERSION
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: WEB_CONCURRENCY
        value: 2 
      - key: DATABASE_URL
        fromDatabase:
          name: artgallerydb # This name must match the database service name below
          property: connectionString
      # DJANGO_ALLOWED_HOSTS and DJANGO_CSRF_TRUSTED_ORIGINS will be set in Render Dashboard UI

  - type: pserv # PostgreSQL Database service
    name: artgallerydb # Name of your database service
    region: frankfurt 
    plan: free
    # Render will create a PostgreSQL database for you on the free plan.
    # You can specify postgresqlVersion if needed, e.g.
    # postgresqlVersion: '15'