# Generated by Django 5.2.1 on 2025-05-24 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Leave blank to auto-generate from title.', max_length=255, unique=True)),
                ('description', models.TextField()),
                ('image_placeholder_url', models.URLField(blank=True, help_text='URL to a placeholder image for now.', max_length=500, null=True)),
                ('is_for_sale_direct', models.BooleanField(default=False)),
                ('direct_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_for_auction', models.BooleanField(default=False)),
                ('auction_start_time', models.DateTimeField(blank=True, null=True)),
                ('auction_end_time', models.DateTimeField(blank=True, null=True)),
                ('auction_minimum_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('auction_current_highest_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction_current_highest_bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_bids_on', to=settings.AUTH_USER_MODEL)),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_artworks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
