# Generated by Django 5.2.1 on 2025-05-25 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('direct_buy', 'Direct Buy'), ('auction_win', 'Auction Win')], max_length=20)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dekont_image', models.FileField(blank=True, null=True, upload_to='dekonts/')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('dekont_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('admin_action_at', models.DateTimeField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True, help_text='Reason for rejection, or other notes.', null=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='artworks.artwork')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
    ]
