# Generated by Django 5.2.1 on 2025-05-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='GallerySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_iban', models.CharField(default='TR33 0006 1005 1978 6457 8413 26', max_length=100)),
                ('bank_account_holder', models.CharField(default='Art Gallery İzmir', max_length=200)),
                ('contact_phone', models.CharField(default='+90 555 555 5555', max_length=20)),
                ('payment_instructions', models.TextField(blank=True, help_text='Additional instructions for payment, e.g., reference number format.')),
            ],
        ),
    ]
