# Generated by Django 5.2.1 on 2025-06-13 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_remove_artwork_auction_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='auction_winner',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='auction_winning_price',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='auction_current_highest_bidder',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_bids_on', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='auction_minimum_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='auction_scheduled_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='auction_signup_deadline',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='auction_signup_offset_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='auction_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='auction_status',
            field=models.CharField(choices=[('not_configured', 'Not Configured'), ('draft', 'Draft'), ('configured', 'Configured / Upcoming'), ('signup_open', 'Sign-up Open'), ('awaiting_start', 'Awaiting Start'), ('live', 'Live Auction')], default='not_configured', max_length=30),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='last_bid_time',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
