# Generated by Django 5.2.1 on 2025-06-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_remove_artwork_auction_winner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='dekont_image',
        ),
        migrations.AddField(
            model_name='transaction',
            name='dekont_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='dekont_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='dekont_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
