# Generated by Django 5.2.1 on 2025-06-29 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0008_remove_transaction_dekont_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='description',
        ),
    ]
